name: whatsapp_clone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  emoji_picker_flutter: ^1.5.2
  flutter_emoji: ^2.4.0
  cached_network_image: ^3.2.3
  path_provider: ^2.0.15
  open_file_plus: ^3.4.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/landing_img.png
    - assets/images/NOT_SENT.png
    - assets/images/SENT.png
    - assets/images/DELIVERED.png
    - assets/images/READ.png
    - assets/images/dark/chat_bg.png
    - assets/images/chat_bg.png
    - assets/images/logo.png
    - assets/images/avatar.png

  fonts:
    - family: AzeretMono
      fonts:
        - asset: assets/fonts/AzeretMono-Regular.ttf